### ISSUE TITLE
Problem with small data.samples

### ISSUE THREAD

**Issue by Naeemkh** [NSAPH-Software/GPCERF#24]
```
Error in chol.default(x_cov) : 
  the leading minor of order 6 is not positive definite
Calls: <Anonymous> ... compute_w_corr -> t -> t -> solve -> chol -> chol.default
Execution halted
```

**Comment by boyuren158** [comment]
I did some experimenting and the reason for this error message is in function compute_w_corr. Specifically, there is a bug in the function on line 51: colMeans should be colSums. It can only fix the issue partially but will still throw out error when `weights` is highly concentrated on a single observation. This is the main issue we need to address now.

**Comment by Naeemkh** [comment]
We also replaced weighted correlation approach with the package wCorr.
