### ISSUE TITLE
balanced correlations

### ISSUE THREAD

**Issue by juandavidgutier** [NSAPH-Software/GPCERF#43]
Hello @NSAPH-Software

I am new with Gaussian Processes (GP), and I am reproducing the script of the vignette named Full-Gaussian-Processes.Rmd, of the package GPCERF. My question is how I can get the GP-induced (Adjusted) absolute correlations between the treatment and all six covariates in the example of that vignette (cf1-cf6), or how can I evaluate the performance of covariates balance?

I will appreciate a lot your cooperation.

Regards,

Juan David

**Comment by boyuren158** [comment]
Hi Juan,

Thanks so much for your interest in using GPCERF. The current version of GPCERF does not return the correlations but only uses it for parameter tuning. However, we are staging a change in the main function that will also return the absolute correlations based on the selected hyper-parameters. This change should be consolidated early next week and I'll let you know once it's done.

Boyu

**Comment by juandavidgutier** [comment]
Hi @boyuren158 

Thanks for your response. However, reviewing the documentation of the function "compute_m_sigma" it says that the function produces a list, where the element "cb" is a vector of absolute weighted correlation of each covariate to the exposure. My question is: can I compare the values of this "cb" element of the list, with the absolute values of the raw correlations, and use it as a measure of the covariates balance performance? It means that a good covariates balance should produce correlation coefficients with values close to 0, isn't it?

Best regards,

Juan

**Comment by boyuren158** [comment]
Hi @juandavidgutier, you are correct. If you'd like to use the compute_m_sigma directly, then you will have the cb for a particular set of hyper-paramters and by comparing that with the correlations between exposure and covariates in the original data, you'd have an idea whether the GP achieve covariate balance. The ideal situation is like you said - zero correlation after running compute_m_sigma. That being said, our plan eventually is to hide this function and the user will only have access to the two estimate_cerf functions. This is the reason I mentioned earlier that new release will have the cb also retured by the two estimate_cerf functions.

Best,
Boyu

**Comment by juandavidgutier** [comment]
Hi @boyuren158,

Thanks for your answer and the explanation about the function.

Best regards,

Juan
