### ISSUE TITLE
JOSS paper should at least briefly discuss other GP packages

### ISSUE THREAD

**Issue by martinmodrak** [NSAPH-Software/GPCERF#68]
The paper currently discusses only R packages for causal inference, but avoids relating GPCERF to other packages for Gaussian process inference.

It appears to me that GPCERF performs several steps: 1) searching for hyperparameters, 2) computing the generalized propensity score (GPS) 3) fitting a 2D Gaussian process for the outcome using the exposure and propensity score.

It seems that at least in principle, any package capable of 2D GP processing can be used for step 3. If that's correct, it IMHO should be at least briefly discussed and explained how the GP implementation in this package relates to other common GP packages. Especially since some packages would allow for estimating the alpha, beta and gamma hyperparameters jointly with the GP, which would IMHO be a superior approach (if not, a brief explanation why is IMHO warranted).

It is also possible I am missing something about the nature of the computations in GPCERF, so feel free to correct any misunderstanding.

**Comment by Naeemkh** [comment]
Thanks @martinmodrak, You are correct. There are other R packages that perform Gaussian process regression. The main reason we chose to not directly use these packages is that all of them utilize traditional hyper-parameter tuning approaches, either by sampling from the posterior distributions of the hyper-parameters or by maximizing the marginal likelihood function, while the tuning approach we proposed in the paper is based on maximizing covariate balancing. We updated the paper to reflect this discussion.
