### ISSUE TITLE
Other Paper Draft Comments

### ISSUE THREAD

**Issue by andrewherren** [NSAPH-Software/GPCERF#90]
Some other minor comments on the paper draft upon further review:

> In the context of causal inference for continuous exposures, the main target for inference is the so-called casual exposure response function (CERF), which is defined as the expectation of the counterfactual outcomes over a range of exposure levels in a given population.

I think the CERF is **_a_** target for continuous exposure causal inference, but not necessarily _**the main**_ target (there are many). Furthermore, the line about `expectation of the counterfactual outcomes over a range of exposure levels` reads a bit unclearly and makes it seem as if the expectation is being integrated over the exposure variable rather than the covariates (the math in the next line of the paper disambiguates this, but I would go ahead and clear that up in the text as well).

> This model implicitly performs non-parametric regression of $Y$ on $W$ and $s(W,C)$, and thus we can recover $p(Y|W, s(W,C))$ with high accuracy by using the posterior mean of the model parameters

This part of the paper explains how you get $p(Y | W, s(W, C))$ but not how you get $E[Y(w)]$. It's fine if that's beyond the scope of a JOSS paper, but I would at least add a note that deriving $E[Y(w)]$ from $p(Y | W, s(W, C))$ is covered in more detail in Ren et al (2021).

> In other words, by confining the exposure level of interest to the aforementioned interval, the probability of being exposed to any of the exposure level should be strictly positive given any arbitrary values of the covariates.

This is inaccurate. With finite sample sizes, it is entirely possible to have regions of the covariate space with probability mass concentrated on a small set of observed values of the exposure variable, W.

**Comment by Naeemkh** [comment]
Thank you, we have incorporated all these points into our revised manuscript.
